# Generated by Django 3.2 on 2022-05-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_movierecommendationtagstable_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieRecommendationTagsTable',
        ),
    ]
