# Generated by Django 3.2 on 2022-05-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_movierecommendationtagstable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieRecommendationTagsTable',
        ),
    ]
